// Teams + the invite-only signup flow. Everything here talks to the
// `teams`, `invites` and `services` tables from supabase/schema_v2.sql via
// the same db.js shim the rest of the app uses.
import { db, randomId } from './db.js';
import { supabase } from './supabaseClient.js';

export async function listTeams() {
  const snap = await db.collection('teams').orderBy('createdAt', 'asc').get();
  return snap.docs.map((d) => Object.assign({ id: d.id }, d.data()));
}

export async function createTeam(name) {
  const id = 'team_' + randomId().slice(0, 8);
  await db.doc('teams/' + id).set({ id, name, managerId: null, createdAt: new Date().toISOString() });
  return id;
}

export async function assignTeamManager(teamId, managerId) {
  await db.doc('teams/' + teamId).update({ managerId });
  // Requires schema_v6.sql's "profiles writable" policy (Admin can update
  // ANY profile row, not just their own) - before that fix, this call
  // silently updated zero rows whenever managerId wasn't the caller's own
  // uid, which is exactly why this only ever seemed to work when Admin
  // assigned themselves.
  //
  // round 8.7/schema_v10: this now GRANTS 'manager' alongside whatever
  // roles the person already holds, rather than overwriting their role
  // outright (see grantRole() below) - promoting someone to a team's point
  // of contact no longer wipes out, say, their existing Sr. Video Editor
  // role.
  if (managerId) { await grantRole(managerId, 'manager'); await db.doc('profiles/' + managerId).update({ teamId }); }
}

// ---------------------------------------------------------------------------
// Multiple roles per employee (schema_v10.sql's profileRoles table). The
// legacy single `profiles.role` column is still kept in sync (to the first
// role in the set) purely as a convenience fallback for any display spot
// that hasn't been updated to read the full list - see schema_v10.sql's own
// comment on this for the full reasoning. profileRoles is the real,
// authoritative source everywhere access is actually decided.
// ---------------------------------------------------------------------------

// Every profileRoles row, grouped by userId - one fetch, not one query per
// person, since the roster/admin pages need every employee's role list at
// once. { [userId]: ['role1','role2',...] }
export async function listAllRoles() {
  const snap = await db.collection('profileRoles').get();
  const byUser = {};
  snap.docs.forEach((d) => {
    const row = d.data();
    (byUser[row.userId] = byUser[row.userId] || []).push(row.role);
  });
  return byUser;
}

export async function listRolesFor(uid) {
  const snap = await db.collection('profileRoles').where('userId', '==', uid).get();
  return snap.docs.map((d) => d.data().role);
}

// Grants ONE role in addition to whatever the person already holds, without
// touching their other roles - used by assignTeamManager() above (promoting
// someone to a team's point of contact should never demote them out of a
// job-title role they already hold).
export async function grantRole(uid, role) {
  await db.doc('profileRoles/' + uid + '_' + role).set({ userId: uid, role, createdAt: new Date().toISOString() });
  await db.doc('profiles/' + uid).update({ role });
}

// Sets an employee's FULL role set at once - the Admin roster's multi-select
// checklist calls this with everything currently checked, and this diffs it
// against what they hold today (only ever added/removed roles actually
// touch the database, not a delete-everything-then-reinsert-everything).
export async function assignRoles(uid, roles) {
  const wanted = Array.from(new Set(roles || []));
  const current = await listRolesFor(uid);
  const toAdd = wanted.filter((r) => current.indexOf(r) === -1);
  const toRemove = current.filter((r) => wanted.indexOf(r) === -1);
  await Promise.all([
    ...toAdd.map((r) => db.doc('profileRoles/' + uid + '_' + r).set({ userId: uid, role: r, createdAt: new Date().toISOString() })),
    ...toRemove.map((r) => db.doc('profileRoles/' + uid + '_' + r).delete()),
  ]);
  // Legacy convenience column - see the top-of-section comment.
  await db.doc('profiles/' + uid).update({ role: wanted[0] || null });
}

// Clears a team's point-of-contact without touching whoever currently
// holds the 'manager' role there (their role/team assignment is untouched -
// this only clears the label shown as "who to contact for this team").
export async function clearTeamManager(teamId) {
  await db.doc('teams/' + teamId).update({ managerId: null });
}

// ---------------------------------------------------------------------------
// Invites. The "code" is the invites row's own id (a short random string
// generated by the database) - see schema_v2.sql's handle_new_user() for why
// it's a secret code and not just an email match.
//
// `roles` is an array (round 8.7/schema_v10.sql - an invite can now grant
// more than one role at once, same as an existing employee's role set can
// hold more than one). `role` (singular) is still written too, set to the
// first chosen role - the legacy/display fallback column, same reasoning as
// profiles.role - schema_v10.sql's invites_roles_not_empty/roles_domain
// constraints are what actually enforce the array is well-formed.
// ---------------------------------------------------------------------------
export async function createInvite(email, roles, teamId, invitedBy) {
  const roleList = Array.isArray(roles) ? roles : [roles];
  const { data, error } = await supabase
    .from('invites')
    .insert({ email: email.trim().toLowerCase(), role: roleList[0], roles: roleList, teamId, invitedBy })
    .select()
    .single();
  if (error) throw error;
  return data;
}

export async function listInvites(teamId) {
  let q = supabase.from('invites').select('*').order('createdAt', { ascending: false });
  if (teamId) q = q.eq('teamId', teamId);
  const { data, error } = await q;
  if (error) throw error;
  return data || [];
}

// Cancel a still-pending invite (never one that's already been used to
// create an account - see schema_v9.sql's delete policy, which enforces
// that at the database level too, not just here). Needs schema_v9.sql,
// which is what actually adds the delete policy that lets this succeed at
// all - before it, RLS denied every delete on `invites` outright.
export async function cancelInvite(id) {
  await db.doc('invites/' + id).delete();
}

// ---------------------------------------------------------------------------
// Services - the controlled vocabulary. scope is 'global' or 'team'.
// ---------------------------------------------------------------------------
export async function listServices() {
  const snap = await db.collection('services').orderBy('createdAt', 'asc').get();
  return snap.docs.map((d) => Object.assign({ id: d.id }, d.data()));
}

export async function createService(name, scope, teamId, subTasks, createdBy) {
  const id = 'svc_' + randomId().slice(0, 8);
  await db.doc('services/' + id).set({
    id, name, scope, teamId: scope === 'team' ? teamId : null,
    subTasks: subTasks || [], createdBy, createdAt: new Date().toISOString(),
  });
  return id;
}

export async function deleteService(id) {
  await db.doc('services/' + id).delete();
}
