// Teams + the invite-only signup flow. Everything here talks to the
// `teams`, `invites` and `services` tables from supabase/schema_v2.sql via
// the same db.js shim the rest of the app uses.
import { db, randomId } from './db.js';
import { supabase } from './supabaseClient.js';

export async function listTeams() {
  const snap = await db.collection('teams').orderBy('createdAt', 'asc').get();
  return snap.docs.map((d) => Object.assign({ id: d.id }, d.data()));
}

export async function createTeam(name) {
  const id = 'team_' + randomId().slice(0, 8);
  await db.doc('teams/' + id).set({ id, name, managerId: null, createdAt: new Date().toISOString() });
  return id;
}

export async function assignTeamManager(teamId, managerId) {
  await db.doc('teams/' + teamId).update({ managerId });
  // Requires schema_v6.sql's "profiles writable" policy (Admin can update
  // ANY profile row, not just their own) - before that fix, this call
  // silently updated zero rows whenever managerId wasn't the caller's own
  // uid, which is exactly why this only ever seemed to work when Admin
  // assigned themselves.
  if (managerId) await db.doc('profiles/' + managerId).update({ role: 'manager', teamId });
}

// Clears a team's point-of-contact without touching whoever currently
// holds the 'manager' role there (their role/team assignment is untouched -
// this only clears the label shown as "who to contact for this team").
export async function clearTeamManager(teamId) {
  await db.doc('teams/' + teamId).update({ managerId: null });
}

// ---------------------------------------------------------------------------
// Invites. The "code" is the invites row's own id (a short random string
// generated by the database) - see schema_v2.sql's handle_new_user() for why
// it's a secret code and not just an email match.
// ---------------------------------------------------------------------------
export async function createInvite(email, role, teamId, invitedBy) {
  const { data, error } = await supabase
    .from('invites')
    .insert({ email: email.trim().toLowerCase(), role, teamId, invitedBy })
    .select()
    .single();
  if (error) throw error;
  return data;
}

export async function listInvites(teamId) {
  let q = supabase.from('invites').select('*').order('createdAt', { ascending: false });
  if (teamId) q = q.eq('teamId', teamId);
  const { data, error } = await q;
  if (error) throw error;
  return data || [];
}

// Cancel a still-pending invite (never one that's already been used to
// create an account - see schema_v9.sql's delete policy, which enforces
// that at the database level too, not just here). Needs schema_v9.sql,
// which is what actually adds the delete policy that lets this succeed at
// all - before it, RLS denied every delete on `invites` outright.
export async function cancelInvite(id) {
  await db.doc('invites/' + id).delete();
}

// ---------------------------------------------------------------------------
// Services - the controlled vocabulary. scope is 'global' or 'team'.
// ---------------------------------------------------------------------------
export async function listServices() {
  const snap = await db.collection('services').orderBy('createdAt', 'asc').get();
  return snap.docs.map((d) => Object.assign({ id: d.id }, d.data()));
}

export async function createService(name, scope, teamId, subTasks, createdBy) {
  const id = 'svc_' + randomId().slice(0, 8);
  await db.doc('services/' + id).set({
    id, name, scope, teamId: scope === 'team' ? teamId : null,
    subTasks: subTasks || [], createdBy, createdAt: new Date().toISOString(),
  });
  return id;
}

export async function deleteService(id) {
  await db.doc('services/' + id).delete();
}
